<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Вывод" data-toc-modified-id="Вывод-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Вывод</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
from IPython.display import display
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score

In [2]:
warnings.filterwarnings("ignore")

In [3]:
data=pd.read_csv('/datasets/insurance.csv')
display(data.head())

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

In [4]:
def fun_date(data):
    print('**Общая информация датафрейма**')
    print(data.info())
    print('-------------------------------------------------------------------------------------------------------------')
    print('**Просмотр статистических данных**')
    print(data.describe())
    print('-------------------------------------------------------------------------------------------------------------')
    print('**Вывод рандомных строк датафрейма**')
    print(data.sample(n=3, random_state=1))
    print('-------------------------------------------------------------------------------------------------------------')
    print('**Вывод первых пяти строк датафрейма**')
    print(data.head())
    print('-------------------------------------------------------------------------------------------------------------')
    print('**Вывод количесва дубликатов датафрейма**')
    print(data.duplicated().sum())
    print('-------------------------------------------------------------------------------------------------------------')
    print('**Вывод количесва пропущеных значений датафрейма**')
    print(data.isnull().sum())
    print('-------------------------------------------------------------------------------------------------------------')
print(fun_date(data))

**Общая информация датафрейма**
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
Пол                  5000 non-null int64
Возраст              5000 non-null float64
Зарплата             5000 non-null float64
Члены семьи          5000 non-null int64
Страховые выплаты    5000 non-null int64
dtypes: float64(2), int64(3)
memory usage: 195.4 KB
None
-------------------------------------------------------------------------------------------------------------
**Просмотр статистических данных**
               Пол      Возраст      Зарплата  Члены семьи  Страховые выплаты
count  5000.000000  5000.000000   5000.000000  5000.000000        5000.000000
mean      0.499000    30.952800  39916.360000     1.194200           0.148000
std       0.500049     8.440807   9900.083569     1.091387           0.463183
min       0.000000    18.000000   5300.000000     0.000000           0.000000
25%       0.000000    24.000000  33300.000000     0.000000   

In [5]:
data.drop_duplicates().reset_index(drop= True)

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0       1     41.0   49600.0            1                  0
1       0     46.0   38000.0            1                  1
2       0     29.0   21000.0            0                  0
3       0     21.0   41700.0            2                  0
4       1     28.0   26100.0            0                  0
...   ...      ...       ...          ...                ...
4842    0     28.0   35700.0            2                  0
4843    0     34.0   52400.0            1                  0
4844    0     20.0   33900.0            2                  0
4845    1     22.0   32700.0            3                  0
4846    1     28.0   40600.0            1                  0

[4847 rows x 5 columns]

<font color='blue'>153 дубликата, лучше от них избавиться, чтобы посмотреть качесво модели на реальных результатах, а не на задвойниках
</font>

In [6]:
data['Возраст']=data['Возраст'].astype('int')

<font color='blue'>Данные изучены и преобразованы, можем приступать к работе!
</font>

In [7]:
features=data.drop('Страховые выплаты', axis=1)
target=data['Страховые выплаты']
model=LinearRegression()
model.fit(features, target)
pred=model.predict(features)
print(r2_score(target, pred))


0.42494550286668


<font color='blue'>
Качесво получилось 0.42, не то чтобы хорошо, но и не плохо) 
Сделаем обратную матрицу и умножим её на фичи, посмотрим что получится</font>

In [8]:
#random_matrix = np.matrix(np.random.randint(10, size=(int(input('rows=')), int(input('cols=')))))
random_matrix = np.matrix(np.random.randint(10, size=(4,4)))
print('Исходная матрица:')
print(random_matrix)
print()
L = np.linalg.inv(random_matrix)
print("Обратная матрица:")
print(L)
print()
features1 = features.dot(L)
features1

Исходная матрица:
[[5 8 1 6]
 [2 9 8 4]
 [1 9 5 7]
 [7 3 3 7]]

Обратная матрица:
[[ 0.11035422  0.09673025 -0.21730245  0.06743869]
 [ 0.16076294  0.05449591 -0.04495913 -0.1239782 ]
 [-0.15122616  0.126703   -0.01702997  0.07425068]
 [-0.11444142 -0.17438692  0.24386921  0.09673025]]



0            1           2            3
0    -7494.230245  6286.625341 -846.503406  3677.914850
1    -5739.313351  4817.046322 -648.963215  2815.919619
2    -3171.087193  2662.343324 -358.933243  1555.668937
3    -6302.983651  5284.310627 -710.606267  3093.843324
4    -3942.391008  3308.570845 -445.958447  1934.538828
...           ...          ...         ...          ...
4995 -5394.501362  4524.474114 -608.741144  2647.471390
4996 -7918.899183  6640.915531 -893.655313  3886.617166
4997 -5123.580381  4295.972752 -577.727520  2514.811989
4998 -4941.791553  4143.960490 -557.354905  2425.627384
4999 -6135.284741  5145.589918 -692.649183  3011.270436

[5000 rows x 4 columns]

In [9]:
model1=LinearRegression()
model1.fit(features1, target)
pred1=model1.predict(features1)
print(r2_score(target, pred1))

0.4249455028666643


<font color='blue'>
 Качество модели после переобучения практически не изменилось </font>

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:** R2 не изменится если домножать только фичи, если домножить матрицу полностью -  R2 будет запредельно большим

**Обоснование:** Насколько я понимаю, связь между признаками линейная, просто при умножении добавляется коэффициенты в виде матрицы, но по итогу на результат повлиять не должно


## Алгоритм преобразования

**Алгоритм**
Видим, что умножение на матрицу действительно не влияет(значимо) на обучаемость линейной регрессии
**Обоснование:** 
Попробуем обосновать это математически:

Линейная регрессия, чтобы найти прямую с нужными коэффициентами, использует формулу $$\omega=(X^TX)^{-1}X^Ty$$где $X$ — матрица с признаками, а $y$ — вектор целевого признака.

Предсказание результатов осуществляется по формуле $a=X_1\omega$ где $X_1$ — некоторые новые строки признаков, а $a$ — предсказания модели по этим признакам.

Посмотрим, что будет, если домножить наши признаки на некоторую случайную матрицу $A$, при условии что число её строк равно числу столбцов $X$ (умножение возможно), и $А$ — обратима, то есть существует такая $A^{-1}$ что $AA^{-1}=E$, где $E$ - единичная матрица.

$$
a = Xw = XEw = XAA^{-1}w = (XA)A^{-1}w = (XA)w'
$$





После домножения при новом обучении регрессии, модель найдет новые коэффициенты, назовем их: $$w'$$

$$
w = (X^T X)^{-1} X^T y
$$
\
$$
w' = ((XA)^T XA)^{-1} (XA)^T y
$$
$$
w' = (A^T (X^T X) A)^{-1} (XA)^T y
$$
$$
w' = (A^T (X^T X) A)^{-1} A^T X^T y
$$
$$
w' = A^{-1} (X^T X)^{-1} (A^T)^{-1} A^T X^T y
$$
$$
w' = A^{-1} (X^T X)^{-1} E X^T y
$$
\
$$
w' = A^{-1}w
$$
$$\omega^{'} = ((XA)^T(XA))^{-1}(XA)^Ty$$  

Подставим ее в формулу предсказания результатов:

$$a^{'} = X_1A\omega^{'} = X_1A((XA)^T(XA))^{-1}(XA)^Ty=X_1A(XA))^{-1}((XA)^T))^{-1}(XA)^Ty=X_1X^{-1}y$$

## Проверка алгоритма

In [10]:
features2=np.array([features])
features3=np.rot90(features2, 2)
target=list(reversed(target))

model2=LinearRegression()
model2.fit(features3[0,:,:], target)
pred2=model2.predict(features3[0,:,:])
print(r2_score(target, pred2))

0.42494550286668


<font color='blue'>
Стабильность – признак мастерства!
</font>

## Вывод

Если рассматривать передачу данных третьим лицам, то к преимуществам данного подхода можно отнести, в первую очередь, ощутимую экономию ресурсов по сравнению с некоторыми известными алгоритмами шифрования.

Недостаток данного метода, что он работает только с матрицей 4х4, и если мы будем задействовать матрицу больших размеров, то это приведет к увеличению затраченных ресурсов, но и эту задачу можно будет решить!